
export const Images={
    Aditya : require('../Team/GDSC_team/Aditya Gaikwad.jpg'),
    Advait: require('../Team/GDSC_team/advait.JPG'),
    Alisha: require('../Team/GDSC_team/Alisha.JPG'),
    Aman: require('../Team/GDSC_team/Aman.JPG'),
    Arnav: require('../Team/GDSC_team/Arnav .JPG'),
    Arya: require('../Team/GDSC_team/Arya.jpg'),
    Aum: require('../Team/GDSC_team/Aum.JPG'),
    Ayushk: require('../Team/GDSC_team/Ayush_kamthe.jpg'),
    Ayush: require('../Team/GDSC_team/Ayush.JPG'),
    Bhavesh: require('../Team/GDSC_team/Bhavesh.JPG'),
    Dheraj: require('../Team/GDSC_team/Dheraj.JPG'),
    Harsh: require('../Team/GDSC_team/Harsh.JPG'),
    Ishan: require('../Team/GDSC_team/Ishan.JPG'),
    Kavya: require('../Team/GDSC_team/Kavya.JPG'),
    Kush: require('../Team/GDSC_team/Kush.jpg'),
    Malhar: require('../Team/GDSC_team/Malhar.JPG'),
    Ojas: require('../Team/GDSC_team/ojas.jpg'),
    Pranav: require('../Team/GDSC_team/Pranav.JPG'),
    Pushkar: require('../Team/GDSC_team/Pushkar.JPG'),
    Rohit: require('../Team/GDSC_team/Rohit.jpg'),
    Sahil: require('../Team/GDSC_team/Sahil.JPG'),
    Sahill: require('../Team/GDSC_team/Sahill.JPG'),
    Samruddhi: require('../Team/GDSC_team/sam.jpg'),
    Sejal: require('../Team/GDSC_team/Sejal.JPG'),
    Shashank: require('../Team/GDSC_team/Shashank.JPG'),
    Shringaar: require('../Team/GDSC_team/Shringaar.jpg'),
    Vedant: require('../Team/GDSC_team/Vedant.jpg'),
    Vishal: require('../Team/GDSC_team/Vishal.JPG'),
    Yash: require('../Team/GDSC_team/Yash.png'),
    Purva:require("../Team/GDSC_team/Purva.jpg"),
    Piyush:require("../Team/GDSC_team/piyush.jpeg"),
    Shre:require("../Team/GDSC_team/Shre.jpeg"),
    Jay:require("../Team/GDSC_team/Jay.jpeg"),
    Ashwin:require("../Team/GDSC_team/Ashwin.jpeg"),
    Yash:require("../Team/GDSC_team/Yash.jpeg"),
}
