export const Images = {
  Aditya: require("./GDSC_team/Aditya Gaikwad.jpg"),
  Advait: require("./GDSC_team/advait.JPG"),
  Alisha: require("./GDSC_team/Alisha.JPG"),
  Aman: require("./GDSC_team/Aman.JPG"),
  Arnav: require("./GDSC_team/Arnav .JPG"),
  Arya: require("./GDSC_team/Arya.jpg"),
  Aum: require("./GDSC_team/Aum.JPG"),
  Ayushk: require("./GDSC_team/Ayush_kamthe.jpg"),
  Ayush: require("./GDSC_team/Ayush.JPG"),
  Bhavesh: require("./GDSC_team/Bhavesh.JPG"),
  Dheraj: require("./GDSC_team/Dheraj.JPG"),
  Harsh: require("./GDSC_team/Harsh.JPG"),
  Ishan: require("./GDSC_team/Ishan.JPG"),
  Kavya: require("./GDSC_team/Kavya.JPG"),
  Kush: require("./GDSC_team/Kush.jpg"),
  Malhar: require("./GDSC_team/Malhar.JPG"),
  Ojas: require("./GDSC_team/ojas.jpg"),
  Pranav: require("./GDSC_team/Pranav.JPG"),
  Pushkar: require("./GDSC_team/Pushkar.JPG"),
  Rohit: require("./GDSC_team/Rohit.jpg"),
  Sahil: require("./GDSC_team/Sahil.JPG"),
  Sahill: require("./GDSC_team/Sahill.JPG"),
  Samruddhi: require("./GDSC_team/sam.jpg"),
  Sejal: require("./GDSC_team/Sejal.JPG"),
  Shashank: require("./GDSC_team/Shashank.JPG"),
  Shringaar: require("./GDSC_team/Shringaar.jpg"),
  Vedant: require("./GDSC_team/Vedant.jpg"),
  Vishal: require("./GDSC_team/Vishal.JPG"),
  Yash1: require("./GDSC_team/Yash1.png"),
  Purva: require("./GDSC_team/Purva.jpg"),
  Piyush: require("./GDSC_team/piyush.jpeg"),
  Shre: require("./GDSC_team/Shre.jpeg"),
  Jay: require("./GDSC_team/Jay.jpeg"),
  Ashwin: require("./GDSC_team/Ashwin.jpeg"),
  Yash: require("./GDSC_team/Yash.jpeg"),
};
